-- :name 1 :!
-- :result :one
DO $$
BEGIN

ALTER TABLE Posts ALTER COLUMN pst_time TYPE timestampz;
ALTER TABLE Posts DROP COLUMN pst_shorturl;

ALTER TABLE Sessions DROP COLUMN SES_USR_ID_FK;

ALTER TABLE SESSIONS
ADD COLUMN SES_USR_ID_FK integer REFERENCES USERS(USR_ID_PK);

DROP TABLE Location;

CREATE TABLE IF NOT EXISTS LOCATION (
LOC_ID varchar(10) PRIMARY KEY,
LOC_ID_PK serial,
LOC_Alias varchar(20) NOT NULL,
LOC_State varchar(2)
);

INSERT INTO Location (LOC_ID, LOC_ALIAS, LOC_STATE)
VALUES ('28607', 'Boone', 'NC');

PERFORM F_DBVERSION(1);

END$$;

-- :name 2 :!
-- :result :one
DO $$
BEGIN

ALTER TABLE POSTS DROP COLUMN PST_LOC_FK;
ALTER TABLE POSTS ADD COLUMN PST_LOC_FK INT;

ALTER TABLE SESSIONS DROP COLUMN SES_LOC_FK;
ALTER TABLE SESSIONS ADD COLUMN SES_LOC_FK INT;

PERFORM F_DBVERSION(2);

END $$;

-- :name 3 :!
DO $$
BEGIN

ALTER TABLE USERS ALTER COLUMN USR_USERNAME DROP NOT NULL;
ALTER TABLE USERS ALTER COLUMN USR_EMAIL DROP NOT NULL;
ALTER TABLE USERS ALTER COLUMN USR_CREATEDON TYPE TIMESTAMPTZ;

PERFORM F_DBVERSION(3);

END $$;

-- :name 4 :!

DO $$
BEGIN

-- ALTER TABLE POSTS ALTER COLUMN PST_LOC_FK NOT NULL;

ALTER TABLE SESSIONS ALTER COLUMN SES_USR_ID_FK SET DEFAULT -1;

PERFORM F_DBVERSION(4);

END $$

-- :name 5 :!

DO $$
BEGIN

ALTER TABLE POSTS ADD COLUMN PST_PARENT_FK INT REFERENCES POSTS(PST_ID_PK);

PERFORM F_DBVERSION(5);

END $$

-- :name 6 :!
DO $$
BEGIN

ALTER TABLE POSTS ADD COLUMN PST_HASCOMMENTS BOOLEAN;

PERFORM F_DBVERSION(6);

END $$


-- yeet
