<template>
    <div>
        <b-modal 
            size='sm'
            hide-header
            hide-footer
            @hidden="hide">
            <qrcode :value="getNewCode()" :options="{width: 250}"></qrcode>
        </b-modal>
    </div>
</template>

<script>
import VueQrcode from '@chenfengyuan/vue-qrcode';

export default {
    name: 'QRCode',
    components: {
        'qrcode': VueQrcode
    },
    methods: {
        getNewCode: function () {
            return "https://www.google.com"; 
            // this will be a url with cookie generated by server
        }, 
        hide: function() {
            this.$emit('closeDialog');
        }
    },
    mounted() {
        this.$children[0].show();
    }
}
</script>

<style>

</style>