<template>
    <div>
        <b-modal 
            hide-header
            hide-footer
            @hidden="hide">
            <canvas id="qr"></canvas>
        </b-modal>
    </div>
</template>

<script>
import QRCode from 'qrcode'

export default {
    name: 'QRCode',
    methods: {
        getNewCode: function () {
            return "https://www.google.com"; 
            // this will be a string with cookie generated by server
        }, 
        hide: function() {
            this.$emit('closeDialog');
        }
    },
    mounted() {
        var canvas = document.getElementById('qr')
        QRCode.toCanvas(canvas, 'sample text', {});

        this.$children[0].show();
    }
}
</script>

<style>

</style>